# Generated by Django 5.1.6 on 2025-02-13 04:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['processed', 'created_at'], name='queue_app_q_process_fa4afd_idx')],
            },
        ),
    ]
