# Generated by Django 5.1.6 on 2025-02-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueitem',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
